@startuml

skinparam defaultFontName Microsoft YaHei UI
start
    note
    meter_645_re()
    ====
    * meter_645.c
    end note
    while(有新数据)is(true)
        if(接收数组位置超出范围)then(false)
        else(true)
        :数据计数置零;
        endif
        if(步骤为2)then(true)
            :接收数据写入数组;
            if(一帧接收完成)then(false)
            else(true)
                if(帧尾)then(错误)
                else(正确)
                    :数据校验;
                    if(校验)then(错误)
                    else(正确)
                        :接受数据发送到数据队列;
                    endif
                endif
            endif
        elseif(步骤为1)then(true)
            :接收数据写入数组;
            if(接收数据个数达到8并且数据正确)then(true)
            :标记步骤为2;
            endif
        elseif(步骤为0且帧头正确)then(true)
            :协议头写入数组头部，数据位置设为1;
            :标记步骤为1;
        endif    
    endwhile(false)
stop
@enduml

